# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RxAccumulator' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'RxSwift', '~> 4.1.1'
  pod 'RxCocoa', '~> 4.1.1'

  # Pods for RxAccumulator

  target 'RxAccumulatorTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RxAccumulatorUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
