# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
platform :ios, '10.0'
target 'RxFeed' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RxFeed
pod "RxSwift", "~> 3.6.1"
pod "RxCocoa", "~> 3.6.1"

pod 'RxFeedback'

  target 'RxFeedTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RxFeedUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
